version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=myapp
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-setup.sql:/docker-entrypoint-initdb.d/db-setup.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pg_data:
